// <auto-generated />
using System;
using Jookli.UserAccess.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Jookli.UserAccess.Infrastructure.Migrations
{
    [DbContext(typeof(UserAccessContext))]
    [Migration("20231021185631_21102023Migration")]
    partial class _21102023Migration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Jookli.BuildingBlocks.Application.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OccuredOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ProcessedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OutboxMessages");
                });

            modelBuilder.Entity("Jookli.BuildingBlocks.Infrastructure.InternalCommands.InternalCommand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ProcessedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("InternalCommands");
                });

            modelBuilder.Entity("Jookli.UserAccess.Domain.Entities.Message.MessageEntity", b =>
                {
                    b.Property<Guid>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MessageContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MessagePhoneNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("MessageTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserEntityUserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MessageId");

                    b.HasIndex("UserEntityUserID");

                    b.ToTable("MessageEntity");
                });

            modelBuilder.Entity("Jookli.UserAccess.Domain.Entities.User.UserEntity", b =>
                {
                    b.Property<Guid>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfLastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<bool>("IsMicrophoneAllowed")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhoneNumber")
                        .HasColumnType("int");

                    b.Property<bool>("Premium")
                        .HasColumnType("bit");

                    b.Property<bool>("PushNotifications")
                        .HasColumnType("bit");

                    b.HasKey("UserID");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Jookli.UserAccess.Domain.Entities.VoiceMessage.VoiceMessageEntity", b =>
                {
                    b.Property<Guid>("VoiceMessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserEntityUserID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("VoiceMessageDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("VoiceMessageLength")
                        .HasColumnType("int");

                    b.HasKey("VoiceMessageId");

                    b.HasIndex("UserEntityUserID");

                    b.ToTable("VoiceMessageEntity");
                });

            modelBuilder.Entity("Jookli.UserAccess.Domain.Entities.Message.MessageEntity", b =>
                {
                    b.HasOne("Jookli.UserAccess.Domain.Entities.User.UserEntity", null)
                        .WithMany("MessagesReceived")
                        .HasForeignKey("UserEntityUserID");
                });

            modelBuilder.Entity("Jookli.UserAccess.Domain.Entities.VoiceMessage.VoiceMessageEntity", b =>
                {
                    b.HasOne("Jookli.UserAccess.Domain.Entities.User.UserEntity", null)
                        .WithMany("VoiceMessagesReceived")
                        .HasForeignKey("UserEntityUserID");
                });

            modelBuilder.Entity("Jookli.UserAccess.Domain.Entities.User.UserEntity", b =>
                {
                    b.Navigation("MessagesReceived");

                    b.Navigation("VoiceMessagesReceived");
                });
#pragma warning restore 612, 618
        }
    }
}
